AGENTS = [
    {
        "id": "executive",
        "name": "Executive Agent",
        "role": "Plans, decomposes, delegates, and verifies complex tasks. Entry point for general requests.",
        "visible": True,
        "icon": "🧠",
    },
    {
        "id": "planner",
        "name": "Planner Agent",
        "role": "Decomposes goals into structured subtasks, timelines, and execution plans.",
        "visible": True,
        "icon": "📋",
    },
    {
        "id": "researcher",
        "name": "Research Agent",
        "role": "Performs deep research, fact-finding, and competitive analysis.",
        "visible": True,
        "icon": "🔍",
    },
    {
        "id": "builder",
        "name": "Code Builder Agent",
        "role": "Creates production-ready code, repo structures, deployment scripts, and artifacts.",
        "visible": True,
        "icon": "🔨",
    },
    {
        "id": "executor",
        "name": "Executor Agent",
        "role": "Executes approved backend commands and returns logs, stdout, and results.",
        "visible": True,
        "icon": "💻",
    },
    {
        "id": "browser",
        "name": "Browser Agent",
        "role": "Automates web navigation, page extraction, screenshots, and form interactions.",
        "visible": True,
        "icon": "🌐",
    },
    {
        "id": "memory_agent",
        "name": "Memory Agent",
        "role": "Retrieves past context, outcomes, and conversations to inform current tasks.",
        "visible": True,
        "icon": "🗄️",
    },
    {
        "id": "monitor",
        "name": "Monitor Agent",
        "role": "Tracks system health, uptime, API endpoints, and alert conditions.",
        "visible": True,
        "icon": "📡",
    },
    {
        "id": "telegram_agent",
        "name": "Telegram Agent",
        "role": "Manages Telegram bot integration, command routing, and user notifications.",
        "visible": True,
        "icon": "✈️",
    },
    {
        "id": "reward_scout",
        "name": "Reward Discovery Agent",
        "role": "Identifies bug bounties, hackathons, grants, and freelance income opportunities.",
        "visible": True,
        "icon": "💰",
    },
    {
        "id": "bounty_hunter",
        "name": "Bug Bounty Agent",
        "role": "Generates OWASP checklists for authorized security testing programs.",
        "visible": True,
        "icon": "🎯",
    },
]
